# Nom de votre Github Actions
name: CI/CD APP JAVA

# Triggers ou déclencheurs
# Lors d'un push sur la branch main
on:
  push:
    branches: [ "main" ]

# Déclenchement des jobs lors d'un push
jobs:

  # Etape 1: se connecte en ssh et créer un répertoire
  create-folder:
    name: create-folder
    runs-on: ubuntu-latest
  
    steps:
  
      # Action 1
    - name: Create folder on remote VM
      uses: appleboy/ssh-action@v1.0.3

      # Rajouter les secrets dans settings => secrets and variables
      with:
        host: ${{ secrets.OWNHOST }}
        username: ${{ secrets.OWNUSERNAME }}
        password: ${{ secrets.OWNPASSWORD }}
        port: ${{ secrets.OWNPORT }}
        
        #script à exécuter
        script: mkdir -p /home/vagrant/quizz